### ISSUE TITLE
Error at step 1  : bootstrapin

### ISSUE THREAD

**Issue by sihnabil** [jensbodal/ng1-ng2-hybrid#19]
Hi, 
Thanks for your repository and guide. i tried following the step but I had probleme at the first step : bootstraping .  I got this error.  do you have some explanation of this error ? 
![error](https://user-images.githubusercontent.com/32969444/32443868-d296b7fa-c300-11e7-8e98-6e020db351c0.png)

**Comment by jensbodal** [comment]
I'm not sure, my only guess would be that the post-install script didn't run and bower didn't install the front end dependencies.  I just checked out the repo at step-1, installed and started the app and the page loaded fine.


```
git clone git@github.com:jensbodal/ng1-ng2-hybrid.git
cd ng1-ng2-hybrid
git checkout -b step-1 step-1
npm i
grunt 
```

**Comment by jensbodal** [comment]
Closing for now. Let me know if you're still having issues.
